// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/post/post.proto

package post

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description          int64    `protobuf:"varint,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_de323a772ac9b83f, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Post) GetDescription() int64 {
	if m != nil {
		return m.Description
	}
	return 0
}

func (m *Post) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type PostCreateRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCreateRequest) Reset()         { *m = PostCreateRequest{} }
func (m *PostCreateRequest) String() string { return proto.CompactTextString(m) }
func (*PostCreateRequest) ProtoMessage()    {}
func (*PostCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de323a772ac9b83f, []int{1}
}

func (m *PostCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCreateRequest.Unmarshal(m, b)
}
func (m *PostCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCreateRequest.Marshal(b, m, deterministic)
}
func (m *PostCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCreateRequest.Merge(m, src)
}
func (m *PostCreateRequest) XXX_Size() int {
	return xxx_messageInfo_PostCreateRequest.Size(m)
}
func (m *PostCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostCreateRequest proto.InternalMessageInfo

func (m *PostCreateRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PostCreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostCreateRequest) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type PostDeleteRequest struct {
	PostId               int64    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostDeleteRequest) Reset()         { *m = PostDeleteRequest{} }
func (m *PostDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*PostDeleteRequest) ProtoMessage()    {}
func (*PostDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de323a772ac9b83f, []int{2}
}

func (m *PostDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDeleteRequest.Unmarshal(m, b)
}
func (m *PostDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDeleteRequest.Marshal(b, m, deterministic)
}
func (m *PostDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDeleteRequest.Merge(m, src)
}
func (m *PostDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_PostDeleteRequest.Size(m)
}
func (m *PostDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostDeleteRequest proto.InternalMessageInfo

func (m *PostDeleteRequest) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PostDeleteRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type PostDeleteResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostDeleteResponse) Reset()         { *m = PostDeleteResponse{} }
func (m *PostDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*PostDeleteResponse) ProtoMessage()    {}
func (*PostDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de323a772ac9b83f, []int{3}
}

func (m *PostDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDeleteResponse.Unmarshal(m, b)
}
func (m *PostDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDeleteResponse.Marshal(b, m, deterministic)
}
func (m *PostDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDeleteResponse.Merge(m, src)
}
func (m *PostDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_PostDeleteResponse.Size(m)
}
func (m *PostDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostDeleteResponse proto.InternalMessageInfo

func (m *PostDeleteResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type PostsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsRequest) Reset()         { *m = PostsRequest{} }
func (m *PostsRequest) String() string { return proto.CompactTextString(m) }
func (*PostsRequest) ProtoMessage()    {}
func (*PostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de323a772ac9b83f, []int{4}
}

func (m *PostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsRequest.Unmarshal(m, b)
}
func (m *PostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsRequest.Marshal(b, m, deterministic)
}
func (m *PostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsRequest.Merge(m, src)
}
func (m *PostsRequest) XXX_Size() int {
	return xxx_messageInfo_PostsRequest.Size(m)
}
func (m *PostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostsRequest proto.InternalMessageInfo

type PostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsResponse) Reset()         { *m = PostsResponse{} }
func (m *PostsResponse) String() string { return proto.CompactTextString(m) }
func (*PostsResponse) ProtoMessage()    {}
func (*PostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de323a772ac9b83f, []int{5}
}

func (m *PostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsResponse.Unmarshal(m, b)
}
func (m *PostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsResponse.Marshal(b, m, deterministic)
}
func (m *PostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsResponse.Merge(m, src)
}
func (m *PostsResponse) XXX_Size() int {
	return xxx_messageInfo_PostsResponse.Size(m)
}
func (m *PostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostsResponse proto.InternalMessageInfo

func (m *PostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "Post")
	proto.RegisterType((*PostCreateRequest)(nil), "PostCreateRequest")
	proto.RegisterType((*PostDeleteRequest)(nil), "PostDeleteRequest")
	proto.RegisterType((*PostDeleteResponse)(nil), "PostDeleteResponse")
	proto.RegisterType((*PostsRequest)(nil), "PostsRequest")
	proto.RegisterType((*PostsResponse)(nil), "PostsResponse")
}

func init() {
	proto.RegisterFile("proto/post/post.proto", fileDescriptor_de323a772ac9b83f)
}

var fileDescriptor_de323a772ac9b83f = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0x03, 0xb4, 0x68, 0x07, 0x4b, 0xe2, 0x18, 0x95, 0x60, 0x4c, 0x08, 0x7a, 0xe0, 0xd0,
	0xac, 0xb1, 0x3e, 0x41, 0xa3, 0x1e, 0x7a, 0x33, 0xf8, 0x00, 0x0d, 0xb2, 0x73, 0xd8, 0x04, 0xbb,
	0xc8, 0x2e, 0xbe, 0x84, 0x2f, 0x6d, 0x76, 0xd9, 0x03, 0xf8, 0xa7, 0x17, 0x92, 0xef, 0xdb, 0x99,
	0xf9, 0x7d, 0x33, 0x01, 0xce, 0xdb, 0x4e, 0x6a, 0x79, 0xd7, 0x4a, 0xa5, 0xed, 0x87, 0x59, 0x9d,
	0xb7, 0x30, 0x7b, 0x91, 0x4a, 0x63, 0x0c, 0xbe, 0xe0, 0x89, 0x97, 0x79, 0x45, 0x50, 0xfa, 0x82,
	0xe3, 0x25, 0x1c, 0xf5, 0x8a, 0xba, 0x9d, 0xe0, 0x89, 0x6f, 0xcd, 0xd0, 0xc8, 0x2d, 0xc7, 0x0c,
	0x22, 0x4e, 0xaa, 0xee, 0x44, 0xab, 0x85, 0xdc, 0x27, 0x81, 0x7d, 0x1c, 0x5b, 0x78, 0x0d, 0x50,
	0x77, 0x54, 0x69, 0xe2, 0xbb, 0x4a, 0x27, 0xb3, 0xcc, 0x2b, 0x16, 0xe5, 0xc2, 0x39, 0x1b, 0x9d,
	0xbf, 0xc3, 0xa9, 0x21, 0x3e, 0x5a, 0xa3, 0xa4, 0x8f, 0x9e, 0x94, 0x1e, 0xe3, 0xbc, 0x43, 0x38,
	0xdf, 0x4e, 0x3b, 0x80, 0x0b, 0x7e, 0xe2, 0x9e, 0x07, 0xdc, 0x13, 0x35, 0x34, 0xc1, 0x99, 0x1b,
	0x8c, 0x70, 0x46, 0x6e, 0xff, 0x5f, 0x3b, 0x5f, 0x01, 0x8e, 0xc7, 0xa8, 0x56, 0xee, 0x15, 0xe1,
	0x05, 0x84, 0x4a, 0x57, 0xba, 0x57, 0x76, 0xcc, 0x71, 0xe9, 0x54, 0x1e, 0xc3, 0x89, 0xa9, 0x56,
	0x8e, 0x97, 0xaf, 0x60, 0xe9, 0xb4, 0x6b, 0xbc, 0x82, 0xb9, 0x21, 0x9a, 0xbe, 0xa0, 0x88, 0xd6,
	0x73, 0x66, 0x9e, 0xcb, 0xc1, 0x5b, 0x7f, 0x79, 0x10, 0x19, 0xfd, 0x4a, 0xdd, 0xa7, 0xa8, 0x09,
	0x6f, 0x20, 0x1c, 0xae, 0x85, 0xc8, 0x7e, 0x9d, 0x2e, 0x1d, 0x7a, 0xf1, 0x1e, 0xc2, 0x21, 0x9c,
	0x2b, 0x9a, 0x2c, 0x9c, 0x9e, 0xb1, 0x3f, 0xd2, 0xdf, 0x42, 0xb0, 0x69, 0x1a, 0x5c, 0xb2, 0x71,
	0xd6, 0x34, 0x66, 0x93, 0xa8, 0x6f, 0xa1, 0xfd, 0x51, 0x1e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x1e, 0x72, 0x20, 0xf7, 0x41, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PostService service

type PostServiceClient interface {
	Create(ctx context.Context, in *PostCreateRequest, opts ...client.CallOption) (*Post, error)
	Delete(ctx context.Context, in *PostDeleteRequest, opts ...client.CallOption) (*PostDeleteResponse, error)
	All(ctx context.Context, in *PostsRequest, opts ...client.CallOption) (*PostsResponse, error)
}

type postServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPostServiceClient(serviceName string, c client.Client) PostServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "postservice"
	}
	return &postServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *postServiceClient) Create(ctx context.Context, in *PostCreateRequest, opts ...client.CallOption) (*Post, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.Create", in)
	out := new(Post)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Delete(ctx context.Context, in *PostDeleteRequest, opts ...client.CallOption) (*PostDeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.Delete", in)
	out := new(PostDeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) All(ctx context.Context, in *PostsRequest, opts ...client.CallOption) (*PostsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "PostService.All", in)
	out := new(PostsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostService service

type PostServiceHandler interface {
	Create(context.Context, *PostCreateRequest, *Post) error
	Delete(context.Context, *PostDeleteRequest, *PostDeleteResponse) error
	All(context.Context, *PostsRequest, *PostsResponse) error
}

func RegisterPostServiceHandler(s server.Server, hdlr PostServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PostService{hdlr}, opts...))
}

type PostService struct {
	PostServiceHandler
}

func (h *PostService) Create(ctx context.Context, in *PostCreateRequest, out *Post) error {
	return h.PostServiceHandler.Create(ctx, in, out)
}

func (h *PostService) Delete(ctx context.Context, in *PostDeleteRequest, out *PostDeleteResponse) error {
	return h.PostServiceHandler.Delete(ctx, in, out)
}

func (h *PostService) All(ctx context.Context, in *PostsRequest, out *PostsResponse) error {
	return h.PostServiceHandler.All(ctx, in, out)
}
